CREATE TABLE profiles (
  id SERIAL PRIMARY KEY,
  userId INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  username VARCHAR(20) UNIQUE NOT NULL,
  name VARCHAR(20) NOT NULL,
  bio VARCHAR(500),
  img_url VARCHAR(2048),
);
