CREATE TABLE profiles (
  _id SERIAL PRIMARY KEY NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  uuid UUID DEFAULT gen_random_uuid(),
  username VARCHAR(20) UNIQUE NOT NULL,
  name VARCHAR(20) NOT NULL,
  bio VARCHAR(500),
  img_url VARCHAR(2048)
);
